//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class WALLPOST
    {
        public int POSTID { get; set; }
        public int PID { get; set; }
        public string POST { get; set; }
        public int FID { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
    
        public virtual Profiles Profiles { get; set; }
        public virtual Profiles Profiles1 { get; set; }
    }
}
